### ISSUE TITLE
Can shurcooL/go/ctxhttp dependency be removed?

### ISSUE THREAD

**Issue by gmlewis** [shurcooL/graphql#2]
Re: https://github.com/shurcooL/graphql/blob/52ce28a2c9fdfbdb3377232422c7915fa04b678a/graphql.go#L11
the ctxhttp package is being imported, which then refers to https://go-review.googlesource.com/c/24620
which has been merged.
Is it possible to remove the dependency now?

**Comment by shurcooL** [comment]
Hi Glenn,

Thanks for checking in on this. To be clear, the [`ctxhttp`](https://godoc.org/github.com/shurcooL/go/ctxhttp) package comment says:

> It's a copy of "golang.org/x/net/context/ctxhttp" with pre-1.7 support dropped, and "golang.org/x/net/context" import replaced with "context". It exists temporarily until "golang.org/x/net/context/ctxhttp" is updated, **which will happen "in a couple releases" according to https://golang.org/cl/24620.**

Specifically, it exists until `golang.org/x/net/context/ctxhttp` is updated to use `context` instead of the obsolete `golang.org/x/net/context`. It is not waiting on [CL 24620](https://golang.org/cl/24620) to be merged—that happened a long time ago. I referenced that CL because its the source of information that the `golang.org/x/net/context/ctxhttp` update to use `context` will happen "in a couple releases".

Perhaps I should've been more specific there and pointed to the message itself:

https://go-review.googlesource.com/c/24620#message-a0eec577b9152b699a15e9c50c8615654fb3191b

That hasn't happened yet, so I can't quite do this. Otherwise, it would result in both `context` and `golang.org/x/net/context` packages being imported (indirectly), which would be suboptimal.

Now that Go 1.9 final is almost released, perhaps it's very soon that `golang.org/x/net/context/ctxhttp` can be updated and my copy will no longer need to exist.

**Comment by shurcooL** [comment]
I've filed https://github.com/golang/go/issues/21358 to find out what the status of the upstream `ctxhttp` is, and when it can be updated to use the modern `context` import.

**Comment by shurcooL** [comment]
Until that issue is resolved, I'll just note that the `github.com/shurcooL/go/ctxhttp` package is very simple conceptually. Its source is 100% identical to `golang.org/x/net/context/ctxhttp`, except the pre-1.7 support is dropped and "golang.org/x/net/context" import is replaced with "context".

Compare for yourself:

- [ctxhttp.go in golang.org/net/x/context/ctxhttp](https://github.com/golang/net/blob/1c05540f6879653db88113bc4a2b70aec4bd491f/context/ctxhttp/ctxhttp.go)
- [ctxhttp.go in github.com/shurcooL/go/ctxhttp](https://github.com/shurcooL/go/blob/b2ea7b593ffddfdfb43ab719c308c25cb2054db0/ctxhttp/ctxhttp.go)

**Comment by dmitshur** [comment]
Issue https://github.com/golang/go/issues/21358 has been resolved today, so I can finally resolve this issue! 🎉 /cc @gmlewis
